# Generated by Django 5.2 on 2025-04-26 13:15

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "sur_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="город"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo/avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "tg_chat_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Чат ID телеграма",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Активность"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("инструмент", "Инструмент"),
                            ("электрика", "Электрика"),
                            ("сухие смеси", "Сухие смеси"),
                            ("сантехника", "Сантехника"),
                            ("метизы", "Метизы"),
                            ("лкп и гсм", "ЛКП и ГСМ"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_type",
                    models.CharField(
                        choices=[("B2B", "B2B"), ("B2C", "B2C")], max_length=3
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название организации",
                    ),
                ),
                (
                    "o_g_r_n",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="ОГРН"
                    ),
                ),
                (
                    "i_n_n",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Расчетный счет для B2B",
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        related_name="clients",
                        to="tracker.address",
                        verbose_name="Адреса клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["first_name", "sur_name", "last_name", "phone"],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("сотрудник отдела кадров", "Сотрудник отдела кадров"),
                            ("менеджер по продажам", "Менеджер по продажам"),
                            ("менеджер склада", "Менеджер склада"),
                            ("складской оператор", "Складской оператор"),
                            ("инспектор по качеству", "Инспектор по качеству"),
                            ("товаровед", "Товаровед"),
                            ("логист", "Логист"),
                            ("кладовщик", "Кладовщик"),
                            ("комплектовщик", "Комплектовщик"),
                            ("грузчик", "Грузчик"),
                            ("приемщик", "Приемщик"),
                            ("курьер", "Курьер"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "work_vacation",
                    models.BooleanField(default=False, verbose_name="Рабочий отпуск"),
                ),
                (
                    "day_off",
                    models.BooleanField(default=False, verbose_name="Выходные"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["position"],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
