# Generated by Django 5.2 on 2025-04-27 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_shippingzone_order_current_step_order_shipping_zone"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.shippingzone",
                verbose_name="Зона отгрузки (для логистов, курьеров и приемщиков)",
            ),
        ),
    ]
