# Generated by Django 5.2 on 2025-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_employee_shipping_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Чат ID телеграмма"
            ),
        ),
    ]
