# Generated by Django 5.2 on 2025-05-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="client",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
