services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - net
  celery:
    build: .
    command: celery -A config worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - ./.env
    networks:
      - net


  db:
    image: postgres
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - net

  redis:
    image: redis
    volumes:
      - redis_volume:/data
    env_file:
      - ./.env
    networks:
      - net

volumes:
  postgres_data:
  static_volume:
  redis_volume:

networks:
  net:

