# Generated by Django 5.2 on 2025-04-26 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="этаж"),
                ),
                (
                    "apartment",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="номер квартиры"
                    ),
                ),
                (
                    "house",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="номер дома"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="населенный пункт",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="область"
                    ),
                ),
                (
                    "postal_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="почтовый индекс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ["city"],
            },
        ),
        migrations.CreateModel(
            name="OrderEmployeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время назначения",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("assigned", "Назначена"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                        ],
                        default="assigned",
                        max_length=50,
                        verbose_name="Статус задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "История сотрудников заказа",
                "verbose_name_plural": "История сотрудников заказов",
                "ordering": ["assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Обработка заказа"),
                            ("assembly", "Сборка заказа"),
                            ("item_picking", "Сборка товара для заказа"),
                            ("completion", "Укомплектовка товара"),
                            ("to_shipping", "Доставка в зону отгрузки"),
                            ("at_shipping", "Приемка в зоне отгрузки"),
                            ("docs", "Подготовка документов"),
                            ("delivery", "Доставка заказа"),
                            ("delivered", "Заказ доставлен"),
                        ],
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время изменения статуса",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Завершён ли этап?"
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса заказа",
                "verbose_name_plural": "История статусов заказов",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "amount_remains",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "amount_supplier",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество у поставщика"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформления заказа"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сумма заказа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Обработка заказа"),
                            ("assembly", "Сборка заказа"),
                            ("item_picking", "Сборка товара для заказа"),
                            ("completion", "Укомплектовка товара"),
                            ("to_shipping", "Доставка в зону отгрузки"),
                            ("at_shipping", "Приемка в зоне отгрузки"),
                            ("docs", "Подготовка документов"),
                            ("delivery", "Доставка заказа"),
                            ("delivered", "Заказ доставлен"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.address",
                        verbose_name="Адрес доставки",
                    ),
                ),
            ],
        ),
    ]
