# Generated by Django 5.2 on 2025-04-26 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="orderemployeehistory",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="orderemployeehistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_employee_history",
                to="tracker.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="employee",
            field=models.ManyToManyField(
                through="tracker.OrderEmployeeHistory",
                to="users.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_status_history",
                to="tracker.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="tracker.OrderProduct",
                to="tracker.product",
                verbose_name="Товары",
            ),
        ),
    ]
