# Generated by Django 5.2 on 2025-04-27 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("city", "Город"),
                            ("district", "Район"),
                            ("region", "Область"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Название зоны",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание зоны"
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона отгрузки",
                "verbose_name_plural": "Зоны отгрузки",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("assembly", "Сборка заказа"),
                    ("item_picking", "Сборка товара для заказа"),
                    ("completion", "Укомплектовка товара"),
                    ("to_shipping", "Доставка в зону отгрузки"),
                    ("at_shipping", "Приемка в зоне отгрузки"),
                    ("docs", "Подготовка документов"),
                    ("delivery", "Доставка заказа"),
                    ("delivered", "Заказ доставлен"),
                ],
                default="processing",
                max_length=50,
                verbose_name="Текущий этап",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.shippingzone",
                verbose_name="Зона отгрузки",
            ),
        ),
    ]
