# Generated by Django 5.2 on 2025-04-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_shippingzone_order_current_step_order_shipping_zone"),
        ("users", "0002_employee_shipping_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
    ]
