# Generated by Django 5.2 on 2025-04-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_order_department"),
        ("users", "0002_employee_shipping_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
    ]
