# Generated by Django 5.2 on 2025-04-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_orderproduct_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="department",
        ),
    ]
