# Generated by Django 5.2 on 2025-04-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_remove_orderproduct_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="department",
        ),
    ]
