# Generated by Django 5.2 on 2025-04-27 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_remove_order_department"),
        ("users", "0002_employee_shipping_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("assembly", "Сборка заказа"),
                    ("item_picking", "Сборка товара для заказа"),
                    ("to_shipping", "Доставка в зону отгрузки"),
                    ("at_shipping", "Приемка в зоне отгрузки"),
                    ("docs", "Подготовка документов"),
                    ("delivery", "Доставка заказа"),
                    ("delivered", "Заказ доставлен"),
                ],
                default="processing",
                max_length=50,
                verbose_name="Текущий этап",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("assembly", "Сборка заказа"),
                    ("item_picking", "Сборка товара для заказа"),
                    ("to_shipping", "Доставка в зону отгрузки"),
                    ("at_shipping", "Приемка в зоне отгрузки"),
                    ("docs", "Подготовка документов"),
                    ("delivery", "Доставка заказа"),
                    ("delivered", "Заказ доставлен"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("assembly", "Сборка заказа"),
                    ("item_picking", "Сборка товара для заказа"),
                    ("to_shipping", "Доставка в зону отгрузки"),
                    ("at_shipping", "Приемка в зоне отгрузки"),
                    ("docs", "Подготовка документов"),
                    ("delivery", "Доставка заказа"),
                    ("delivered", "Заказ доставлен"),
                ],
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("order created", "Cоздан заказ"),
                            (
                                "Collect the goods and send to the shipment zone",
                                "Соберите товар и отправьте в зону отгрузки",
                            ),
                            ("Collect the product", "Cоберите товар"),
                            (
                                "Take the goods to the shipment zone",
                                "Отвезите товар в зону отгрузки",
                            ),
                            ("Accept the goods", "Примите товар для заказа"),
                            (
                                "Prepare documents for sending an order",
                                "Подготовьте документы для отправки заказа",
                            ),
                            (
                                "Direct the order at the address",
                                "Доставьте заказ по адресу",
                            ),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание задачи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Обработка заказа"),
                            ("assembly", "Сборка заказа"),
                            ("item_picking", "Сборка товара для заказа"),
                            ("to_shipping", "Доставка в зону отгрузки"),
                            ("at_shipping", "Приемка в зоне отгрузки"),
                            ("docs", "Подготовка документов"),
                            ("delivery", "Доставка заказа"),
                            ("delivered", "Заказ доставлен"),
                        ],
                        default="processing",
                        max_length=50,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="users.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tracker.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tracker.task",
                        verbose_name="Родительская задача",
                    ),
                ),
                (
                    "shipment_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.shippingzone",
                        verbose_name="Зона отгрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
