# Generated by Django 5.2 on 2025-04-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_alter_order_current_step_alter_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
