# Generated by Django 5.2 on 2025-05-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_remove_task_id_task_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-status"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_name",
        ),
    ]
