# Generated by Django 5.2 on 2025-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_task_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
