# Generated by Django 5.2 on 2025-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_task_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Обработка заказа"),
                    ("assembly", "Сборка заказа"),
                    ("item_picking", "Сборка товара для заказа"),
                    ("to_shipping", "Доставка в зону отгрузки"),
                    ("at_shipping", "Приемка в зоне отгрузки"),
                    ("docs", "Подготовка документов"),
                    ("delivery", "Доставка заказа"),
                    ("delivered", "Заказ доставлен"),
                ],
                max_length=50,
                verbose_name="Статус задачи",
            ),
        ),
    ]
