# Generated by Django 5.2 on 2025-05-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="shipment_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tracker.shippingzone",
                verbose_name="Зона отгрузки",
            ),
        ),
    ]
