# Generated by Django 5.2 on 2025-05-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_alter_task_shipment_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="parent_task",
        ),
    ]
