# Generated by Django 5.2 on 2025-05-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_remove_task_parent_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="current_step",
        ),
    ]
