# Generated by Django 5.2 on 2025-05-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_remove_order_current_step"),
        ("users", "0002_employee_shipping_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
    ]
