# Generated by Django 5.2 on 2025-05-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_task_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="shipment_zone",
            new_name="shipping_zone",
        ),
    ]
