# Generated by Django 5.2 on 2025-05-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_rename_shipment_zone_task_shipping_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderemployeehistory",
            name="task_status",
        ),
        migrations.AddField(
            model_name="orderemployeehistory",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_histories",
                to="tracker.task",
                verbose_name="Задача",
            ),
        ),
    ]
