# Generated by Django 5.2 on 2025-05-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0019_remove_orderemployeehistory_task_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_tasks",
                to="tracker.task",
            ),
        ),
    ]
